os:
  - linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda env create -f ci/conda_requirements.yml
  - source activate test-microsetta-public
  - pip install -r ci/pip_requirements.txt
  - make install

script:
  - make lint
  - make test-cov
  - make test-install
