os:
  - linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda env create -f ci/test-env.yml
  - source activate test-microsetta-public
  - pip install "connexion[swagger-ui]"
  - pip install ".[dev]"

script:
  - py.test
  - flake8

