openapi: 3.0.0
info:
  description: Public Microsetta RESTful API
  version: "2020.04.10-1"
  title: Public Microsetta RESTful API (OAS 3.0)
servers:
  - url: '/api'

paths:
  '/metadata/category/values/{category}':
    get:
      operationId: microsetta_public_api.api.metadata.category_values
      tags:
        - Metadata
      summary: Get values associated with metadata category
      description: Get values associated with metadata category
      parameters:
        - in: path
          name: category
          description: Metadata category to return values of
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successfuly returned category values
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: number
        '404':
            $ref: '#/components/responses/404NotFound'

  '/metadata/sample_ids':
    get:
      operationId: microsetta_public_api.api.metadata.filter_sample_ids
      tags:
        - Metadata
      summary: Get samples associated with query
      description: Get samples associated with query
      parameters:
        - in: query
          name: age_cat
          schema:
            type: string
            example: '30s'
        - in: query
          name: bmi_cat
          schema:
            type: string
            example: 'Normal'
        - in: query
          name: taxonomy
          description: Filter IDs to those present in the table associated with `taxonomy`
          schema:
            type: string
            example: 'genus-level-taxonomy'
        - in: query
          name: alpha_metric
          description: Filter IDs to those present in the data for `alpha_metric`
          schema:
            $ref: '#/components/schemas/alphaMetric'

      responses:
        '200':
          description: Successfully returned sample ids
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sampleIdList"
        '404':
          $ref: '#/components/responses/404NotFound'


  '/diversity/alpha/metrics/available':
    get:
      operationId: microsetta_public_api.api.diversity.alpha.available_metrics_alpha
      tags:
        - Diversity
      summary: Get available alpha diversity metrics
      description: Get available alpha diversity metrics
      responses:
        '200':
          description: Successfully returned alpha diversity metrics
          content:
            application/json:
              schema:
                type: object
                required:
                  - alpha_metrics
                properties:
                  alpha_metrics:
                    type: array
                    items:
                      $ref: '#/components/schemas/alphaMetric'
                    example:
                      - "faith_pd"
                      - "observed_otus"
                      - "chao1"

  '/diversity/alpha/single/{alpha_metric}/{sample_id}':
    get:
      operationId: microsetta_public_api.api.diversity.alpha.get_alpha
      tags:
        - Diversity
      summary: Get single sample alpha diversity
      description: Get single sample alpha diversity
      parameters:
        - $ref: '#/components/parameters/sampleId'
        - $ref: '#/components/parameters/alphaMetric'
      responses:
        '200':
          description: Successfully return alpha diversity information
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_id:
                    $ref: '#/components/schemas/sampleId'
                  alpha_metric:
                    $ref: '#/components/schemas/alphaMetric'
                  data:
                    type: number
                    example: 7.24
                    description: Alpha diversity value for sample ID with metric
        '404':
          $ref: '#/components/responses/404NotFound'

  '/diversity/alpha/group/{alpha_metric}':
    post:
      operationId: microsetta_public_api.api.diversity.alpha.alpha_group
      tags:
        - Diversity
      summary: Query alpha diversity for a group of samples
      description: Query alpha diversity for a group of samples

      parameters:
        - $ref: '#/components/parameters/alphaMetric'
        - in: query
          name: summary_statistics
          schema:
            type: boolean
            default: true
          description: >
            Indicates whether summary statistics should be returned.
        - in: query
          name: return_raw
          schema:
            type: boolean
            default: false
          description: >
            Indicates whether raw alpha diversity values should be returned.
        - in: query
          name: percentiles
          explode: false
          schema:
            type: array
            items:
              type: number
              minimum: 0
              maximum: 100
              nullable: true
            default: null
            nullable: true
          required: false
          description: >
            Percentiles that should be returned. If not specified, then
            `10,20,30,40,50,60,70,80,90` will be used.
            Ignored if `summary_statistics=false`.

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sampleIdList"

      responses:
        '200':
          description: Successfuly return alpha diversity information
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - alpha_metric
                    properties:
                      alpha_metric:
                        $ref: '#/components/schemas/alphaMetric'
                  - anyOf:
                    - type: object
                      required:
                        - alpha_diversity
                      properties:
                        alpha_diversity:
                          type: object
                          additionalProperties:
                            type: number
                            example: 7.24
                            description: Alpha diversity value of the metric for a given sample ID.
                          example:
                            sample1: 0.1,
                            sample2: 9.01,
                            sample3: 7.24,
                          description: Dictionary of sample ID - alpha diversity value pairs
                    - type: object
                      required:
                        - group_summary
                      properties:
                        group_summary:
                          type: object
                          required:
                            - mean
                            - median
                            - std
                            - group_size
                            - percentile
                            - percentile_values
                          properties:
                            mean:
                              type: number
                              example: 8.47
                            median:
                              type: number
                              example: 8.25
                            std:
                              type: number
                              example: 0.54
                            group_size:
                              type: integer
                              example: 24
                            percentile:
                              type: array
                              items:
                                type: number
                                minimum: 0
                                maximum: 100
                              example:
                                - 0
                                - 24
                                - 49
                                - 74
                                - 99
                            percentile_values:
                              type: array
                              items:
                                type: number
                              example:
                                - 7.15
                                - 7.24
                                - 8.25
                                - 9.01
                                - 9.04

        '404':
          $ref: '#/components/responses/404NotFound'
        '400':
          description: >
            Either `summary_statistics`, `return_raw`, or both are required to be true.

  '/taxonomy/available':
    get:
      operationId: microsetta_public_api.api.taxonomy.resources
      tags:
        - Taxonomy
      summary: Get list of available taxonomy resources
      description: Get list of available taxonomy resources
      responses:
        '200':
          description: Successfully returned taxonomy resources
          content:
            application/json:
              schema:
                type: object
                required:
                  - resources
                properties:
                  resources:
                    type: array
                    items:
                      type: string
                      example: "greengenes"
                    example:
                      - "greengenes"
                      - "silva"

  '/taxonomy/group/{resource}':
    post:
      operationId: microsetta_public_api.api.taxonomy.summarize_group
      tags:
        - Taxonomy
      summary: Get taxonomy information for a group of samples
      description: Get taxonomy information for a group of samples
      parameters:
        - $ref: '#/components/parameters/taxonomyResource'

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sampleIdList"

      responses:
        '200':
          description: Successfuly return taxonomy information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taxonomyFeatures'

        '404':
          $ref: '#/components/responses/404NotFound'

  '/taxonomy/single/{resource}/{sample_id}':
    get:
      operationId: microsetta_public_api.api.taxonomy.single_sample
      tags:
        - Taxonomy
      summary: Get taxonomy information for a sample
      description: Get taxonomy information for a sample
      parameters:
        - $ref: '#/components/parameters/sampleId'
        - $ref: '#/components/parameters/taxonomyResource'

      responses:
        '200':
          description: Successfuly return taxonomy information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/taxonomyFeatures'

        '404':
          $ref: '#/components/responses/404NotFound'

  '/taxonomy/present/group/{resource}':
    post:
      operationId: microsetta_public_api.api.taxonomy.group_taxa_present
      tags:
        - Taxonomy
      summary: Get a DataTable of taxa, broken down by rank, for a list of samples
      description: Get a DataTable of taxa, broken down by rank, for a list of samples
      parameters:
        - $ref: '#/components/parameters/taxonomyResource'

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sampleIdList"

      responses:
        '200':
          description: Successfully return taxonomy table
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sampleDataTable'

        '404':
          $ref: '#/components/responses/404NotFound'

  '/taxonomy/present/single/{resource}/{sample_id}':
    get:
      operationId: microsetta_public_api.api.taxonomy.single_sample_taxa_present
      tags:
        - Taxonomy
      summary: Get a DataTable of taxa, broken down by rank, for a given sample
      description: Get a DataTable of taxa, broken down by rank, for a given sample
      parameters:
        - $ref: '#/components/parameters/sampleId'
        - $ref: '#/components/parameters/taxonomyResource'

      responses:
        '200':
          description: Successfully return taxonomy table
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sampleDataTable'

        '404':
          $ref: '#/components/responses/404NotFound'

components:
  parameters:
    alphaMetric:
      name: alpha_metric
      in: path
      description: An alpha diversity metric
      schema:
        $ref: '#/components/schemas/alphaMetric'
      required: true
    sampleId:
      name: sample_id
      in: path
      description: Unique id specifying a sample associated with a source
      schema:
        $ref: '#/components/schemas/sampleId'
      required: true
    taxonomyResource:
      name: resource
      in: path
      description: An identifier for a taxonomy and feature table resource
      schema:
        type: string
        example: "greengenes"
      required: true

  schemas:
    alphaMetric:
      type: string
      example: "faith_pd"
    sampleId:
      type: string
      example: "sample_15"
    sampleIdList:
      type: object
      required:
        - sample_ids
      additionalProperties: false
      properties:
        sample_ids:
          type: array
          items:
            $ref: '#/components/schemas/sampleId'
          example:
            - "sample1"
            - "sample2"
            - "sample3"
    sampleDataTable:
      type: object
      required:
        - data
        - columns
      properties:
        data:
          type: array
          items:
            type: object
            required:
              - sampleId
            properties:
              sampleId:
                $ref: '#/components/schemas/sampleId'
            example:
              - {
                  "sampleId": "sample1",
                  "Kingdom": "Bacteria",
                  "Genus": "Bacteroides"
                }
              - {
                  "sampleId": "sample1",
                  "Kingdom": "Bacteria",
                  "Genus": "Clostridium"
                }
              - {
                  "sampleId": "sample2",
                  "Kingdom": "Bacteria",
                  "Genus": "Bacteroides"
                }
              - {
                  "sampleId": "sample2",
                  "Kingdom": "Bacteria",
                  "Genus": null
                }
              - {
                  "sampleId": "sample3",
                  "Kingdom": "Bacteria",
                  "Genus": "Clostridium"
                }
        columns:
          type: array
          items:
            type: object
            required:
              - data
            properties:
              data:
                type: string
                example:
                  - "sampleId"
                  - "Kingdom"
                  - "Genus"
    taxonomyFeatures:
      type: object
      required:
        - taxonomy
        - features
        - feature_values
      properties:
        taxonomy:
          type: string
          example: "(((((feature-2)e)d,feature-1)c)b)a;"
        features:
          type: array
          items:
            type: string
          example:
            - "feature-1"
            - "feature-2"
        feature_values:
          type: array
          items:
            type: number
          example:
            - 0.75
            - 0.25
        feature_variances:
          type: array
          items:
            type: number
          example:
            - 0.05
            - 0.11

  responses:
    404NotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            type: object
            additionalProperties: true
