openapi: 3.0.0
info:
  description: Public Microsetta RESTful API
  version: "2020.04.10-1"
  title: Public Microsetta RESTful API (OAS 3.0)
servers:
  - url: '/api'

paths:
  '/diversity/alpha/{alpha_metric}/{sample_id}':
    get:
      operationId: microsetta_public_api.api.diversity.alpha.get_alpha
      tags:
        - Diversity
      summary: Get single sample alpha diversity
      description: Get single sample alpha diversity
      parameters:
        - $ref: '#/components/parameters/sample_id'
        - $ref: '#/components/parameters/alpha_metric'
      responses:
        '200':
          description: Successfuly return alpha diversity information
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_id:
                    $ref: '#/components/schemas/sample_id'
                  alpha_metric:
                    $ref: '#/components/schemas/alpha_metric'
                  data:
                    type: number
                    example: 7.24
                    description: Alpha diversity value for sample ID with metric
        '404':
          $ref: '#/components/responses/404SampleNotFound'

  '/diversity/alpha_group/{alpha_metric}':
    post:
      operationId: microsetta_public_api.api.diversity.alpha.alpha_group
      tags:
        - Diversity
      summary: Query alpha diversity for a group of samples
      description: Query alpha diversity for a group of samples

      parameters:
        - $ref: '#/components/parameters/alpha_metric'

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - sample_ids
              properties:
                sample_ids:
                  type: array
                  items:
                    $ref: '#/components/schemas/sample_id'
                  example:
                    - "sample1"
                    - "sample2"
                    - "sample3"

      responses:
        '200':
          description: Successfuly return alpha diversity information
          content:
            application/json:
              schema:
                type: object
                required:
                  - alpha_metric
                  - alpha_diversity
                properties:
                  alpha_metric:
                    $ref: '#/components/schemas/alpha_metric'
                  alpha_diversity:
                    type: object
                    additionalProperties:
                      type: number
                      example: 7.24
                      description: Alpha diversity value for sample ID with metric
                    example:
                      {
                        "sample1": 0.1,
                        "sample2": 9.01,
                        "sample3": 7.24,
                      }
        '404':
          $ref: '#/components/responses/404SampleNotFound'

components:
  parameters:
    alpha_metric:
      name: alpha_metric
      in: path
      description: An alpha diversity metric
      schema:
        $ref: '#/components/schemas/alpha_metric'
      required: true
    sample_id:
      name: sample_id
      in: path
      description: Unique id specifying a sample associated with a source
      schema:
        $ref: '#/components/schemas/sample_id'
      required: true

  schemas:
    alpha_metric:
      # TODO could be enum
      type: string
      example: "faith_pd"
    sample_id:
      type: string
      example: "dae21127-27bb-4f52-9fd3-a2aa5eb5b86f"

  responses:
    404SampleNotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified sample was not found.