openapi: 3.0.0
info:
  description: Public Microsetta RESTful API
  version: "2020.04.10-1"
  title: Public Microsetta RESTful API (OAS 3.0)
servers:
  - url: '/api'

paths:
  '/diversity/metrics/alpha/available':
    get:
      operationId: microsetta_public_api.api.diversity.alpha.available_metrics_alpha
      tags:
        - Diversity
      summary: Get available alpha diversity metrics
      description: Get available alpha diversity metrics
      responses:
        '200':
          description: Successfully returned alpha diversity metrics
          content:
            application/json:
              schema:
                type: object
                required:
                  - alpha_metrics
                properties:
                  alpha_metrics:
                    type: array
                    items:
                      $ref: '#/components/schemas/alpha_metric'
                    example:
                      - "faith_pd"
                      - "observed_otus"
                      - "chao1"

  '/diversity/alpha/{alpha_metric}/{sample_id}':
    get:
      operationId: microsetta_public_api.api.diversity.alpha.get_alpha
      tags:
        - Diversity
      summary: Get single sample alpha diversity
      description: Get single sample alpha diversity
      parameters:
        - $ref: '#/components/parameters/sample_id'
        - $ref: '#/components/parameters/alpha_metric'
      responses:
        '200':
          description: Successfully return alpha diversity information
          content:
            application/json:
              schema:
                type: object
                properties:
                  sample_id:
                    $ref: '#/components/schemas/sample_id'
                  alpha_metric:
                    $ref: '#/components/schemas/alpha_metric'
                  data:
                    type: number
                    example: 7.24
                    description: Alpha diversity value for sample ID with metric
        '404':
          $ref: '#/components/responses/404NotFound'

  '/diversity/alpha_group/{alpha_metric}':
    post:
      operationId: microsetta_public_api.api.diversity.alpha.alpha_group
      tags:
        - Diversity
      summary: Query alpha diversity for a group of samples
      description: Query alpha diversity for a group of samples

      parameters:
        - $ref: '#/components/parameters/alpha_metric'
        - in: query
          name: summary_statistics
          schema:
            type: boolean
            default: true
          description: >
            Indicates whether summary statistics should be returned.
        - in: query
          name: return_raw
          schema:
            type: boolean
            default: false
          description: >
            Indicates whether raw alpha diversity values should be returned.
        - in: query
          name: percentiles
          explode: false
          schema:
            type: array
            items:
              type: number
              minimum: 0
              maximum: 100
              nullable: true
            default: null
            nullable: true
          required: false
          description: >
            Percentiles that should be returned. If not specified, then
            `10,20,30,40,50,60,70,80,90` will be used.
            Ignored if `summary_statistcs=true`.

      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - sample_ids
              properties:
                sample_ids:
                  type: array
                  items:
                    $ref: '#/components/schemas/sample_id'
                  example:
                    - "sample1"
                    - "sample2"
                    - "sample3"

      responses:
        '200':
          description: Successfuly return alpha diversity information
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - alpha_metric
                    properties:
                      alpha_metric:
                        $ref: '#/components/schemas/alpha_metric'
                  - anyOf:
                    - type: object
                      required:
                        - alpha_diversity
                      properties:
                        alpha_diversity:
                          type: object
                          additionalProperties:
                            type: number
                            example: 7.24
                            description: Alpha diversity value of the metric for a given sample ID.
                          example:
                            sample1: 0.1,
                            sample2: 9.01,
                            sample3: 7.24,
                          description: Dictionary of sample ID - alpha diversity value pairs
                    - type: object
                      required:
                        - group_summary
                      properties:
                        group_summary:
                          type: object
                          required:
                            - mean
                            - median
                            - std
                            - group_size
                            - percentile
                            - percentile_values
                          properties:
                            mean:
                              type: number
                              example: 8.47
                            median:
                              type: number
                              example: 8.25
                            std:
                              type: number
                              example: 0.54
                            group_size:
                              type: integer
                              example: 24
                            percentile:
                              type: array
                              items:
                                type: number
                                minimum: 0
                                maximum: 100
                              example:
                                - 0
                                - 24
                                - 49
                                - 74
                                - 99
                            percentile_values:
                              type: array
                              items:
                                type: number
                              example:
                                - 7.15
                                - 7.24
                                - 8.25
                                - 9.01
                                - 9.04

        '404':
          $ref: '#/components/responses/404NotFound'

components:
  parameters:
    alpha_metric:
      name: alpha_metric
      in: path
      description: An alpha diversity metric
      schema:
        $ref: '#/components/schemas/alpha_metric'
      required: true
    sample_id:
      name: sample_id
      in: path
      description: Unique id specifying a sample associated with a source
      schema:
        $ref: '#/components/schemas/sample_id'
      required: true

  schemas:
    alpha_metric:
      type: string
      example: "faith_pd"
    sample_id:
      type: string
      example: "sample_15"

  responses:
    404NotFound:       # Can be referenced as '#/components/responses/404NotFound'
      description: The specified resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              missing_ids:
                type: array
                description: Missing IDs.
                items:
                  $ref: '#/components/schemas/sample_id'
                  example:
                    - "sample1"
                    - "sample2"
