name: test-me
channels:
  - conda-forge
  - qiime2
  - defaults
dependencies:
  - python
  - scipy<=1.8.1
  - flask
  - flask-cors
  - scikit-bio
  - biom-format
  - pandas
  - numpy
  - pyyaml
  - qiime2
  - q2templates
  - q2-types
  - altair
  - jsonschema
